### ISSUE TITLE
ibjpeg-turbo msvc build problem

### ISSUE THREAD

**Issue by VincenzoVR** [cvsandbox/CVSandbox#2]
Hi, 
In the CVSandbox\externals\sources\make\msvc\libjpeg-turbo folder the libjpeg-turbo.sln file is not present, so I cannot make the build with MSVC.
Is it possible to have this file?

**Comment by andrewkirillov** [comment]
Hello,

There is a BAT file which does MSVC build:
https://github.com/cvsandbox/CVSandbox/tree/master/externals/sources/make/msvc/libjpeg-turbo

It will run CMake to get MSVC soluion and do the build. NASM is also needed.

There small read me next to it.
