### ISSUE TITLE
Max resolution for camera

### ISSUE THREAD

**Issue by sekulicb** [cvsandbox/CVSandbox#4]
Hi. My camera resolution goes up to 2560x1440, but the max available that can be set is 1280 x 720. Is there a reason why overall quality of the video is such low quality compared to native camera app on Windows?

Thanks

**Comment by cvsandbox** [comment]
Hello.

Which "native camera app" do you mean? Is it something, which comes with camera drivers? If so, that app may use native API to talk to the camera. CVSandbox uses Direct Show API, which is generic and may have some limitations.

Anyway,without haveing access to the camera and doing some debuging, it is hard to tell.

**Comment by sekulicb** [comment]
Hi, sorry for not responding earlier.

In the Windows OS, on the tablet device there is a "Camera" native app. Something like this:

![camera_9](https://user-images.githubusercontent.com/20758693/87810370-2ebeee80-c85d-11ea-9134-285ac61ab158.png)

This is not related to any specific camera, it's just integrated into Windows, like Windows Defender.

The reason why I ask is because I get funky results with Direct Show API, where sometimes resolution goes up to 1280x960, sometimes 1280x720. Camera app that comes with Windows, offers resolution up to 2560x1440. I think we all agree that for modern device, resolution locked at 1280x720 doesn't offer max details and as such is obsolete. I'm just asking is there a way to setup max resolution with your Library,

Thanks

**Comment by sekulicb** [comment]
Hi,any solution for this?

**Comment by sekulicb** [comment]
Closing because no solution was found
